metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.modules:
- module: system
  enabled: false
- module: elasticsearch
  scope: cluster
  period: 10s
  xpack.enabled: true
  hosts: ${ELASTICSEARCH_HOSTS:}
  username: ${ELASTICSEARCH_USERNAME:}
  password: ${ELASTICSEARCH_PASSWORD:}
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]
  ssl.verification_mode: "certificate"
- module: logstash
  enabled: true
  period: 10s
  hosts: ${LOGSTASH_HOSTS:}
  xpack.enabled: true
- module: rabbitmq
  metricsets: ["node", "queue", "connection", "exchange"]
  enabled: true
  hosts: ${RABBITMQ_HOSTS}
  username: ${RABBITMQ_USERNAME}
  password: ${RABBITMQ_PASSWORD}
- module: prometheus
  enabled: true
  period: 10s
  hosts: ${JINA_HOSTS}
  metrics_path: /


output.elasticsearch:
  hosts: ${ELASTICSEARCH_HOSTS:}
  username: ${ELASTICSEARCH_USERNAME:}
  password: ${ELASTICSEARCH_PASSWORD:}
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]

setup.dashboards:
  enabled: true

setup.kibana:
  host: ${KIBANA_HOST}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
