name: Check Profiles
# Just to make sure Jina Hub doesn't potentially have issues:
concurrency: check-profiles

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pipenv'
      
      - name: Install Pipenv
        run: pipx install pipenv
        
      - name: Install Pipenv Dependencies
        run: pipenv install
        
      - name: Generate profile files
        run: make all-profile-composes --always-make
        timeout-minutes: 10

      - name: Validate profile files
        run: |
          cp .env.ci .env
          mkdir dummy_ingest
          for profile in ./embedder/profiles/*.yml
          do
            echo $profile
            docker compose -f docker-compose.yml -f $profile config > /dev/null
          done
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/verify-changed-files@v11.1
        with:
          files: embedder/profiles/*.yml
        
      - name: Check profiles haven't changed
        if: steps.changed-files.outputs.files_changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Profile files have changed, please regenerate')
          